# Generated by Django 5.0.6 on 2024-05-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/default_img.jpg', null=True, upload_to='img/profile.jpg'),
        ),
    ]
