# Generated by Django 5.0.6 on 2024-05-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_img.jpg', null=True, upload_to='img/profile.jpg'),
        ),
    ]
