# Generated by Django 5.0.6 on 2024-05-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homagram_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_facts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
