# Generated by Django 5.0.6 on 2024-05-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homagram_app', '0005_alter_userprofile_email_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='profile_photo',
            field=models.ImageField(blank=True, default='img/default_img.jpg', null=True, upload_to='img/profile_img'),
        ),
    ]
