# Generated by Django 5.0.6 on 2024-05-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homagram_app', '0006_userprofile_degree_userprofile_pers_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_text',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
