# Generated by Django 5.0.6 on 2024-05-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homagram_app', '0007_remove_socialmedialink_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialink',
            name='resume',
        ),
    ]
